//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_cambios_procesos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apl_Menus
    {
        public int Menu_ID { get; set; }
        public int Estatus_ID { get; set; }
        public Nullable<int> Modulo_ID { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public string Menu_Descripcion { get; set; }
        public string URL_LINK { get; set; }
        public string Nombre_Mostrar { get; set; }
        public Nullable<decimal> Orden { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
        public string Icono { get; set; }
        public Nullable<bool> Visible { get; set; }
        public string Tipo_Menu { get; set; }
    }
}
