//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_cambios_procesos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apl_Usuarios_Permisos
    {
        public int Usuario_Permiso_ID { get; set; }
        public int Usuario_ID { get; set; }
        public int Permiso_ID { get; set; }
    
        public virtual Apl_Permisos_Sistemas Apl_Permisos_Sistemas { get; set; }
        public virtual Apl_Usuarios Apl_Usuarios { get; set; }
    }
}
