//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_cambios_procesos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Validaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_Validaciones()
        {
            this.Ope_Facturas = new HashSet<Ope_Facturas>();
            this.Ope_Facturas1 = new HashSet<Ope_Facturas>();
            this.Cat_Validaciones_Usuarios = new HashSet<Cat_Validaciones_Usuarios>();
        }
    
        public int Validacion_Id { get; set; }
        public int Area_Id { get; set; }
        public string Validacion { get; set; }
        public string Estatus { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
        public Nullable<int> Concepto_ID { get; set; }
    
        public virtual Cat_Areas Cat_Areas { get; set; }
        public virtual Cat_Conceptos Cat_Conceptos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Facturas> Ope_Facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Facturas> Ope_Facturas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Validaciones_Usuarios> Cat_Validaciones_Usuarios { get; set; }
    }
}
