//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_cambios_procesos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entity_CF : DbContext
    {
        public Entity_CF()
            : base("name=Entity_CF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APDoc> APDoc { get; set; }
        public virtual DbSet<Apl_Accesos> Apl_Accesos { get; set; }
        public virtual DbSet<Apl_Empresas> Apl_Empresas { get; set; }
        public virtual DbSet<Apl_Entidades_Empresas> Apl_Entidades_Empresas { get; set; }
        public virtual DbSet<Apl_Estatus> Apl_Estatus { get; set; }
        public virtual DbSet<Apl_Menus> Apl_Menus { get; set; }
        public virtual DbSet<Apl_Modulos> Apl_Modulos { get; set; }
        public virtual DbSet<Apl_Niveles> Apl_Niveles { get; set; }
        public virtual DbSet<Apl_Parametros> Apl_Parametros { get; set; }
        public virtual DbSet<Apl_Permisos_Sistemas> Apl_Permisos_Sistemas { get; set; }
        public virtual DbSet<Apl_Registro_Accesos> Apl_Registro_Accesos { get; set; }
        public virtual DbSet<Apl_Rel_Usuarios_Roles> Apl_Rel_Usuarios_Roles { get; set; }
        public virtual DbSet<Apl_Roles> Apl_Roles { get; set; }
        public virtual DbSet<Apl_Roles_Sucursales> Apl_Roles_Sucursales { get; set; }
        public virtual DbSet<Apl_Usuarios> Apl_Usuarios { get; set; }
        public virtual DbSet<Apl_Usuarios_Password> Apl_Usuarios_Password { get; set; }
        public virtual DbSet<Apl_Usuarios_Permisos> Apl_Usuarios_Permisos { get; set; }
        public virtual DbSet<Cat_Areas> Cat_Areas { get; set; }
        public virtual DbSet<Cat_Conceptos> Cat_Conceptos { get; set; }
        public virtual DbSet<Cat_Cuentas> Cat_Cuentas { get; set; }
        public virtual DbSet<Cat_Entidades> Cat_Entidades { get; set; }
        public virtual DbSet<Cat_Relacion_Entidad_Cuenta> Cat_Relacion_Entidad_Cuenta { get; set; }
        public virtual DbSet<Cat_Validaciones> Cat_Validaciones { get; set; }
        public virtual DbSet<Cat_Validaciones_Usuarios> Cat_Validaciones_Usuarios { get; set; }
        public virtual DbSet<Ope_Anticipos> Ope_Anticipos { get; set; }
        public virtual DbSet<Ope_Facturas> Ope_Facturas { get; set; }
        public virtual DbSet<Ope_Facturas_Anexos> Ope_Facturas_Anexos { get; set; }
        public virtual DbSet<Ope_Facturas_Anticipos> Ope_Facturas_Anticipos { get; set; }
        public virtual DbSet<Ope_Facturas_Movimientos> Ope_Facturas_Movimientos { get; set; }
        public virtual DbSet<Ope_Facturas_Pagos> Ope_Facturas_Pagos { get; set; }
        public virtual DbSet<XREFileAdmin> XREFileAdmin { get; set; }
    }
}
