//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_cambios_procesos
{
    using System;
    using System.Collections.Generic;
    
    public partial class XREFileAdmin
    {
        public string CpnyID { get; set; }
        public System.DateTime Crtd_DateTime { get; set; }
        public string Crtd_Prog { get; set; }
        public string Crtd_User { get; set; }
        public string CuryId { get; set; }
        public double DocAmt { get; set; }
        public string DocDate { get; set; }
        public string DocType { get; set; }
        public string FileNameXML { get; set; }
        public string Folio { get; set; }
        public string FullPath { get; set; }
        public System.DateTime LUpd_DateTime { get; set; }
        public string LUpd_Prog { get; set; }
        public string LUpd_User { get; set; }
        public int NoteId { get; set; }
        public string PmtMthdID { get; set; }
        public string RefNbr { get; set; }
        public string RFC { get; set; }
        public string S4Future01 { get; set; }
        public string S4Future02 { get; set; }
        public double S4Future03 { get; set; }
        public double S4Future04 { get; set; }
        public double S4Future05 { get; set; }
        public double S4Future06 { get; set; }
        public System.DateTime S4Future07 { get; set; }
        public System.DateTime S4Future08 { get; set; }
        public int S4Future09 { get; set; }
        public int S4Future10 { get; set; }
        public string S4Future11 { get; set; }
        public string S4Future12 { get; set; }
        public string Serie { get; set; }
        public short Selected { get; set; }
        public string Status { get; set; }
        public string Sub { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public double User3 { get; set; }
        public double User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public System.DateTime User7 { get; set; }
        public System.DateTime User8 { get; set; }
        public string UUID { get; set; }
        public System.DateTime ValUUIDDate { get; set; }
        public string ValUUIDStatus { get; set; }
        public string VendId { get; set; }
        public string VendName { get; set; }
        public double XMLActSinImp { get; set; }
        public string XMLConcepto { get; set; }
        public string XMLCuryId { get; set; }
        public string XMLFormaDePago { get; set; }
        public string XMLMetodoPago { get; set; }
        public string XMLTaxCodes { get; set; }
        public string XMLTerms { get; set; }
        public string XMLType { get; set; }
        public byte[] tstamp { get; set; }
    }
}
