//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_general_mills
{
    using System;
    using System.Collections.Generic;
    
    public partial class APDoc
    {
        public string Acct { get; set; }
        public short AddlCost { get; set; }
        public double ApplyAmt { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public string ApplyRefNbr { get; set; }
        public string BatNbr { get; set; }
        public int BatSeq { get; set; }
        public double BWAmt { get; set; }
        public string CashAcct { get; set; }
        public string CashSub { get; set; }
        public double ClearAmt { get; set; }
        public System.DateTime ClearDate { get; set; }
        public string CodeType { get; set; }
        public string CpnyID { get; set; }
        public System.DateTime Crtd_DateTime { get; set; }
        public string Crtd_Prog { get; set; }
        public string Crtd_User { get; set; }
        public short CurrentNbr { get; set; }
        public double CuryBWAmt { get; set; }
        public double CuryDiscBal { get; set; }
        public double CuryDiscTkn { get; set; }
        public double CuryDocBal { get; set; }
        public System.DateTime CuryEffDate { get; set; }
        public string CuryId { get; set; }
        public string CuryMultDiv { get; set; }
        public double CuryOrigDocAmt { get; set; }
        public double CuryPmtAmt { get; set; }
        public double CuryRate { get; set; }
        public string CuryRateType { get; set; }
        public double CuryTaxTot00 { get; set; }
        public double CuryTaxTot01 { get; set; }
        public double CuryTaxTot02 { get; set; }
        public double CuryTaxTot03 { get; set; }
        public double CuryTxblTot00 { get; set; }
        public double CuryTxblTot01 { get; set; }
        public double CuryTxblTot02 { get; set; }
        public double CuryTxblTot03 { get; set; }
        public short Cycle { get; set; }
        public short DfltDetail { get; set; }
        public string DirectDeposit { get; set; }
        public double DiscBal { get; set; }
        public System.DateTime DiscDate { get; set; }
        public double DiscTkn { get; set; }
        public short Doc1099 { get; set; }
        public double DocBal { get; set; }
        public string DocClass { get; set; }
        public System.DateTime DocDate { get; set; }
        public string DocDesc { get; set; }
        public string DocType { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Econfirm { get; set; }
        public string Estatus { get; set; }
        public string ExcludeFreight { get; set; }
        public double FreightAmt { get; set; }
        public short InstallNbr { get; set; }
        public System.DateTime InvcDate { get; set; }
        public string InvcNbr { get; set; }
        public string LCCode { get; set; }
        public int LineCntr { get; set; }
        public System.DateTime LUpd_DateTime { get; set; }
        public string LUpd_Prog { get; set; }
        public string LUpd_User { get; set; }
        public string MasterDocNbr { get; set; }
        public short NbrCycle { get; set; }
        public int NoteID { get; set; }
        public short OpenDoc { get; set; }
        public double OrigDocAmt { get; set; }
        public System.DateTime PayDate { get; set; }
        public string PayHoldDesc { get; set; }
        public string PC_Status { get; set; }
        public string PerClosed { get; set; }
        public string PerEnt { get; set; }
        public string PerPost { get; set; }
        public double PmtAmt { get; set; }
        public string PmtID { get; set; }
        public string PmtMethod { get; set; }
        public string PONbr { get; set; }
        public string PrePay_RefNbr { get; set; }
        public string ProjectID { get; set; }
        public int RecordID { get; set; }
        public string RefNbr { get; set; }
        public short Retention { get; set; }
        public double RGOLAmt { get; set; }
        public short Rlsed { get; set; }
        public string S4Future01 { get; set; }
        public string S4Future02 { get; set; }
        public double S4Future03 { get; set; }
        public double S4Future04 { get; set; }
        public double S4Future05 { get; set; }
        public double S4Future06 { get; set; }
        public System.DateTime S4Future07 { get; set; }
        public System.DateTime S4Future08 { get; set; }
        public int S4Future09 { get; set; }
        public int S4Future10 { get; set; }
        public string S4Future11 { get; set; }
        public string S4Future12 { get; set; }
        public short Selected { get; set; }
        public string Status { get; set; }
        public string Sub { get; set; }
        public string Subcontract { get; set; }
        public short TaxCntr00 { get; set; }
        public short TaxCntr01 { get; set; }
        public short TaxCntr02 { get; set; }
        public short TaxCntr03 { get; set; }
        public string TaxId00 { get; set; }
        public string TaxId01 { get; set; }
        public string TaxId02 { get; set; }
        public string TaxId03 { get; set; }
        public double TaxTot00 { get; set; }
        public double TaxTot01 { get; set; }
        public double TaxTot02 { get; set; }
        public double TaxTot03 { get; set; }
        public string Terms { get; set; }
        public double TxblTot00 { get; set; }
        public double TxblTot01 { get; set; }
        public double TxblTot02 { get; set; }
        public double TxblTot03 { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public double User3 { get; set; }
        public double User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public System.DateTime User7 { get; set; }
        public System.DateTime User8 { get; set; }
        public string VendId { get; set; }
        public string VendName { get; set; }
        public byte[] tstamp { get; set; }
    }
}
